name: Run all unit tests

on:
  - push
  - pull_request

jobs:
  test_linux:
    name: Run unit tests on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Run platform-specific tests
        run: ./gradlew linuxX64Test --info

      - name: Run JVM tests
        run: ./gradlew jvmTest --info

  test_macos:
    name: Run unit tests on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Run platform-specific tests
        run: ./gradlew macosX64Test --info

      - name: Run JVM tests
        run: ./gradlew jvmTest --info

  test_windows:
    name: Run unit tests on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Run platform-specific tests
        run: ./gradlew windowsX64Test --info

      - name: Run JVM tests
        run: ./gradlew jvmTest --info
